image: golang:1.10

variables:
  REDIS_ADDRESS: "redis:6379"
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  DOCKER_IMAGE_PREV: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_BEFORE_SHA}"

stages:
  - build
  - test

Docker Build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  before_script:
    - >
      docker login
      --username "${CI_REGISTRY_USER}"
      --password "${CI_REGISTRY_PASSWORD}"
      "${CI_REGISTRY}"
  script:
  - docker pull "${DOCKER_IMAGE_PREV}" || true
  - >
    docker build
    --cache-from "${DOCKER_IMAGE_PREV}"
    --tag "${DOCKER_IMAGE}"
    "${PWD}"
  - docker push "${DOCKER_IMAGE}"

Go Tests:
  image: ${DOCKER_IMAGE}
  stage: test
  services:
    - redis:latest  
  before_script:
    - >
      (
        cd ${GOPATH}/src/gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} || exit
        go get -v golang.org/x/tools/cmd/goimports
        go get -v gopkg.in/alecthomas/gometalinter.v2
        gometalinter.v2 --install
      )
  script:
    - ./go_format.sh
    - ./go_test.sh

