include:
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/go-service.yml'
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/sentry.yml'
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/notify.yml'
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/gke-deploy.yml'

variables:
  DEPLOYMENT_NAME: "gateway"

stages:
  - Prepare
  - Image
  - Release
  - Staging
  - Finalise Staging

Go Lint:
  stage: Prepare
  extends: .Go Service - Go Lint

Go Build:
  stage: Prepare
  extends: .Go Service - Binary Build

Docker Build:
  stage: Image
  extends: .Go Service - Docker Build

Docker Release:
  stage: Release
  extends: .Go Service - Docker Release

Sentry Release:
  stage: Release
  extends: .Sentry - Sentry Release

Deploy:
  stage: Staging
  extends: .Go Service - Deploy Staging

Deploy to GKE:
  stage: Staging
  extends: .GKE - Staging
  script:
  - k8s/render.sh
  - kubectl apply -f k8s/manifest.yaml
  - >
    kubectl rollout status
    --namespace "${K8S_NAMESPACE:-cacophony}"
    deployment.v1.apps/${DEPLOYMENT_NAME}

Sentry Deploy:
  stage: Finalise Staging
  extends: .Sentry - Sentry Deploy
  variables:
    SENTRY_ENV: "staging"
  only:
  - master
Notify Success:
  stage: Finalise Staging
  extends: .Notify - Success
  variables:
    DEPLOYMENT_ENV: "Staging"
  only:
  - master

Notify Error:
  stage: Finalise Staging
  extends: .Notify - Error
  variables:
    DEPLOYMENT_ENV: "Staging"
  only:
  - master
