include:
  - project: 'Cacophony/gitlab-ci'
    ref: master
    file: '/go-service.yml'

variables:
  DEPLOYMENT_NAME: "gateway"

stages:
  - test
  - build
  - staging

Go Lint:
  extends: .Go Lint

Docker Build:
  extends: .Docker Build

Deploy Staging:
  extends: .Deploy Staging
