image: golang:1.10

services:
  - redis:latest

variables:
  REDIS_ADDRESS: "redis:6379"
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

stages:
  - build
  - test

Docker Build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  before_script:
    - >
      docker login
      --username "${CI_REGISTRY_USER}"
      --password "${CI_REGISTRY_PASSWORD}"
      "${CI_REGISTRY}"
  script:
  - docker pull "${DOCKER_IMAGE}" || true
  - docker build -t "${DOCKER_IMAGE}" "${PWD}"
  - docker push "${DOCKER_IMAGE}"

Go Tests:
  stage: test
  before_script:
    # create symlink to ${CI_PROJECT_DIR} in ${GOPATH} and cd there
    - mkdir -p ${GOPATH}/src/gitlab.com/${CI_PROJECT_NAMESPACE}
    - cd ${GOPATH}/src/gitlab.com/${CI_PROJECT_NAMESPACE}
    - ln -s ${CI_PROJECT_DIR}
    - cd ${CI_PROJECT_NAME}
    # install dependencies
    - apt-get update
    - apt-get install libcairo2-dev -y
    # install go dependencies
    # discordgo develop branch
    - go get github.com/bwmarrin/discordgo
    - cd ${GOPATH}/src/github.com/bwmarrin/discordgo
    - git checkout develop
    - cd ${GOPATH}/src/gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
    # all other dependencies
    - go get -v ./...
    # install linters
    - go get -v golang.org/x/tools/cmd/goimports
    - go get -v gopkg.in/alecthomas/gometalinter.v2
    - gometalinter.v2 --install
  script:
    - bash format_go.sh
    - go test -v -race $(go list ./... | grep -v /vendor/)
