apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: cacophony
type: Opaque
stringData:
  discordToken: "{{DISCORD_TOKEN}}"
  amqpDSN: "{{AMQP_DSN}}"
  loggingDiscordWebhook: "{{LOGGING_DISCORD_WEBHOOK}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      namespace: cacophony
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ${DOCKER_IMAGE}
          env:
          - name: PORT
            value: "{{PORT}}"
          - name: ENVIRONMENT
            value: "{{ENVIRONMENT}}"
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: discordToken
          - name: AMQP_DSN
            valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: amqpDSN
          - name: LOGGING_DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: loggingDiscordWebhook
---
